### ISSUE TITLE
[COMMENT] Move the TestxDirector in a sperate package

### ISSUE THREAD

**Issue by b1zzu** [aerogear/graphql-testx#118]
In order to avoid this importing strategy:
```js
import { TestxDirector } from "graphql-testx/dist/src/TestxDirector"
```
that could cause a problem in the future we should split graphql-testx into two packages:
- `graphql-testx` with the `TestxServer` and the `TestxController`
- `graphql-testx-director` with the `TestxDirector` 

For splitting the packages we can use `lerna` and we can copy the structure form graphback and offix.

Currently, we are using the `TestxApi` interface to ensure that the `TestxServer` and the `TestxDirector` implements the same methods, by splitting the packages we should also find a new home for the `TestxApi`, we can do this in two ways:
- Put the `TestxApi` in a new package `graphql-testx-api`
-  Put the `TestxApi` in the `graphql-testx-director` and import it inside `graphql-testx`

If the name director is confusing we can rename it to something else, but I don't want to use the name client because in my opinion is misleading.

As this is a major breaking change we need earlier feedbacks

**Comment by wtrocki** [comment]
Any reason why we cannot export the director from the package? Multiple packages causing very side effects so my recommendation will be to avoid it till there is no other way.

**Comment by b1zzu** [comment]
@wtrocki this is what happened if I try to import the director form the index:
```
 yarn install v1.19.1
warning package.json: No license field
warning graphql-testx-karma-example: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 5.79s.
yarn run v1.19.1
warning package.json: No license field
$ gulp test
[12:00:41] Using gulpfile ~/project/examples/karma/gulpfile.js
[12:00:41] Starting 'test'...

START:
ℹ ｢wdm｣: Hash: 3879665b411e2fff46cc
Version: webpack 4.41.2
Time: 31ms
Built at: 12/11/2019 12:00:41 PM
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
✖ ｢wdm｣: Hash: 00d72d604d2251af210b
Version: webpack 4.41.2
Time: 3651ms
Built at: 12/11/2019 12:00:45 PM
                 Asset      Size               Chunks             Chunk Names
test/mutations.test.js  7.48 MiB  test/mutations.test  [emitted]  test/mutations.test
Entrypoint test/mutations.test = test/mutations.test.js
[../../dist/src/GraphbackClient.js] /home/circleci/project/dist/src/GraphbackClient.js 2.55 KiB {test/mutations.test} [built]
[../../dist/src/GraphbackServer.js] /home/circleci/project/dist/src/GraphbackServer.js 4.04 KiB {test/mutations.test} [built]
[../../dist/src/InMemoryDatabase.js] /home/circleci/project/dist/src/InMemoryDatabase.js 3.21 KiB {test/mutations.test} [built]
[../../dist/src/TestxApi.js] /home/circleci/project/dist/src/TestxApi.js 191 bytes {test/mutations.test} [built]
[../../dist/src/TestxController.js] /home/circleci/project/dist/src/TestxController.js 4.02 KiB {test/mutations.test} [built]
[../../dist/src/TestxDirector.js] /home/circleci/project/dist/src/TestxDirector.js 3.3 KiB {test/mutations.test} [built]
[../../dist/src/TestxServer.js] /home/circleci/project/dist/src/TestxServer.js 9.1 KiB {test/mutations.test} [built]
[../../dist/src/index.js] /home/circleci/project/dist/src/index.js 392 bytes {test/mutations.test} [built]
[../../node_modules/axios/index.js] /home/circleci/project/node_modules/axios/index.js 40 bytes {test/mutations.test} [built]
[./node_modules/chai/index.js] 40 bytes {test/mutations.test} [built]
[./node_modules/chai/lib/chai.js] 1.23 KiB {test/mutations.test} [built]
[./node_modules/cross-fetch/dist/browser-polyfill.js] 12.8 KiB {test/mutations.test} [built]
[./node_modules/graphql-request/dist/src/index.js] 8.34 KiB {test/mutations.test} [built]
[./node_modules/graphql-request/dist/src/types.js] 1.54 KiB {test/mutations.test} [built]
[./test/mutations.test.js] 1.33 KiB {test/mutations.test} [built]
    + 1027 hidden modules

WARNING in /home/circleci/project/node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression
 @ /home/circleci/project/node_modules/express/lib/application.js
 @ /home/circleci/project/node_modules/express/lib/express.js
 @ /home/circleci/project/node_modules/express/index.js
 @ /home/circleci/project/dist/src/TestxController.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/@graphback/core/dist/utils/fileUtils.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/@graphback/core/dist/utils'
 @ /home/circleci/project/node_modules/@graphback/core/dist/utils/fileUtils.js 4:13-26
 @ /home/circleci/project/node_modules/@graphback/core/dist/index.js
 @ /home/circleci/project/node_modules/graphback/dist/index.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/busboy/lib/main.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/busboy/lib'
 @ /home/circleci/project/node_modules/busboy/lib/main.js 1:9-22
 @ /home/circleci/project/node_modules/graphql-upload/lib/processRequest.mjs
 @ /home/circleci/project/node_modules/graphql-upload/lib/index.mjs
 @ /home/circleci/project/node_modules/apollo-server-core/dist/index.js
 @ /home/circleci/project/node_modules/apollo-server-express/dist/index.js
 @ /home/circleci/project/dist/src/GraphbackServer.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/destroy/index.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/destroy'
 @ /home/circleci/project/node_modules/destroy/index.js 14:17-30
 @ /home/circleci/project/node_modules/send/index.js
 @ /home/circleci/project/node_modules/express/lib/response.js
 @ /home/circleci/project/node_modules/express/lib/express.js
 @ /home/circleci/project/node_modules/express/index.js
 @ /home/circleci/project/dist/src/TestxController.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/etag/index.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/etag'
 @ /home/circleci/project/node_modules/etag/index.js 22:12-25
 @ /home/circleci/project/node_modules/send/index.js
 @ /home/circleci/project/node_modules/express/lib/response.js
 @ /home/circleci/project/node_modules/express/lib/express.js
 @ /home/circleci/project/node_modules/express/index.js
 @ /home/circleci/project/dist/src/TestxController.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/express/lib/view.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/express/lib'
 @ /home/circleci/project/node_modules/express/lib/view.js 18:9-22
 @ /home/circleci/project/node_modules/express/lib/application.js
 @ /home/circleci/project/node_modules/express/lib/express.js
 @ /home/circleci/project/node_modules/express/index.js
 @ /home/circleci/project/dist/src/TestxController.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/fs-capacitor/lib/index.mjs
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/fs-capacitor/lib'
 @ /home/circleci/project/node_modules/fs-capacitor/lib/index.mjs 2:0-20 6:32-34 56:4-6 77:33-35 90:10-12 94:8-10 114:6-8 146:6-8 155:6-8
 @ /home/circleci/project/node_modules/graphql-upload/lib/processRequest.mjs
 @ /home/circleci/project/node_modules/graphql-upload/lib/index.mjs
 @ /home/circleci/project/node_modules/apollo-server-core/dist/index.js
 @ /home/circleci/project/node_modules/apollo-server-express/dist/index.js
 @ /home/circleci/project/dist/src/GraphbackServer.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/fs.realpath'
 @ /home/circleci/project/node_modules/fs.realpath/index.js 8:9-22
 @ /home/circleci/project/node_modules/glob/glob.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/utils/graphqlUtils.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/DatabaseMigrater.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/index.js
 @ /home/circleci/project/dist/src/InMemoryDatabase.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/fs.realpath'
 @ /home/circleci/project/node_modules/fs.realpath/old.js 24:9-22
 @ /home/circleci/project/node_modules/fs.realpath/index.js
 @ /home/circleci/project/node_modules/glob/glob.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/utils/graphqlUtils.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/DatabaseMigrater.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/index.js
 @ /home/circleci/project/dist/src/InMemoryDatabase.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/glob/glob.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/glob'
 @ /home/circleci/project/node_modules/glob/glob.js 43:9-22
 @ /home/circleci/project/node_modules/graphql-migrations/dist/utils/graphqlUtils.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/DatabaseMigrater.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/index.js
 @ /home/circleci/project/dist/src/InMemoryDatabase.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/glob/sync.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/glob'
 @ /home/circleci/project/node_modules/glob/sync.js 4:9-22
 @ /home/circleci/project/node_modules/glob/glob.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/utils/graphqlUtils.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/DatabaseMigrater.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/index.js
 @ /home/circleci/project/dist/src/InMemoryDatabase.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/graphql-migrations/dist/database/migrations/DataResourcesManager.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/graphql-migrations/dist/database/migrations'
 @ /home/circleci/project/node_modules/graphql-migrations/dist/database/migrations/DataResourcesManager.js 7:13-26
 @ /home/circleci/project/node_modules/graphql-migrations/dist/database/migrations/index.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/database/index.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/index.js
 @ /home/circleci/project/dist/src/InMemoryDatabase.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/graphql-migrations/dist/migrations/LocalMigrationManager.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/graphql-migrations/dist/migrations'
 @ /home/circleci/project/node_modules/graphql-migrations/dist/migrations/LocalMigrationManager.js 4:13-26
 @ /home/circleci/project/node_modules/graphql-migrations/dist/migrations/index.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/index.js
 @ /home/circleci/project/dist/src/InMemoryDatabase.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/graphql-migrations/dist/utils/graphqlUtils.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/graphql-migrations/dist/utils'
 @ /home/circleci/project/node_modules/graphql-migrations/dist/utils/graphqlUtils.js 3:13-26
 @ /home/circleci/project/node_modules/graphql-migrations/dist/DatabaseMigrater.js
 @ /home/circleci/project/node_modules/graphql-migrations/dist/index.js
 @ /home/circleci/project/dist/src/InMemoryDatabase.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/knex/node_modules/pg-connection-string/index.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/knex/node_modules/pg-connection-string'
 @ /home/circleci/project/node_modules/knex/node_modules/pg-connection-string/index.js 4:9-22
 @ /home/circleci/project/node_modules/knex/lib/util/parse-connection.js
 @ /home/circleci/project/node_modules/knex/lib/knex.js
 @ /home/circleci/project/node_modules/knex/lib/index.js
 @ /home/circleci/project/node_modules/knex/knex.js
 @ /home/circleci/project/dist/src/InMemoryDatabase.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/mime/mime.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/mime'
 @ /home/circleci/project/node_modules/mime/mime.js 2:9-22
 @ /home/circleci/project/node_modules/send/index.js
 @ /home/circleci/project/node_modules/express/lib/response.js
 @ /home/circleci/project/node_modules/express/lib/express.js
 @ /home/circleci/project/node_modules/express/index.js
 @ /home/circleci/project/dist/src/TestxController.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/send/index.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/project/node_modules/send'
 @ /home/circleci/project/node_modules/send/index.js 23:9-22
 @ /home/circleci/project/node_modules/express/lib/response.js
 @ /home/circleci/project/node_modules/express/lib/express.js
 @ /home/circleci/project/node_modules/express/index.js
 @ /home/circleci/project/dist/src/TestxController.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/knex/lib/dialects/mssql/index.js
Module not found: Error: Can't resolve 'mssql/package.json' in '/home/circleci/project/node_modules/knex/lib/dialects/mssql'
 @ /home/circleci/project/node_modules/knex/lib/dialects/mssql/index.js 64:25-54
 @ /home/circleci/project/node_modules/knex/lib/dialects sync ^\.\/.*\/index\.js$
 @ /home/circleci/project/node_modules/knex/lib/knex.js
 @ /home/circleci/project/node_modules/knex/lib/index.js
 @ /home/circleci/project/node_modules/knex/knex.js
 @ /home/circleci/project/dist/src/InMemoryDatabase.js
 @ /home/circleci/project/dist/src/TestxServer.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/express/lib/request.js
Module not found: Error: Can't resolve 'net' in '/home/circleci/project/node_modules/express/lib'
 @ /home/circleci/project/node_modules/express/lib/request.js 18:11-25
 @ /home/circleci/project/node_modules/express/lib/express.js
 @ /home/circleci/project/node_modules/express/index.js
 @ /home/circleci/project/dist/src/TestxController.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js

ERROR in /home/circleci/project/node_modules/get-port/index.js
Module not found: Error: Can't resolve 'net' in '/home/circleci/project/node_modules/get-port'
 @ /home/circleci/project/node_modules/get-port/index.js 2:12-26
 @ /home/circleci/project/dist/src/TestxController.js
 @ /home/circleci/project/dist/src/index.js
 @ ./test/mutations.test.js
ℹ ｢wdm｣: Failed to compile.
11 12 2019 12:00:45.628:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
11 12 2019 12:00:45.629:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
11 12 2019 12:00:45.694:INFO [launcher]: Starting browser ChromeHeadless
11 12 2019 12:00:46.949:INFO [HeadlessChrome 79.0.3945 (Linux 0.0.0)]: Connected on socket sWo7j2REjTWBo33wAAAA with id 5058029
HeadlessChrome 79.0.3945 (Linux 0.0.0) ERROR
  Uncaught Error: Cannot find module 'fs'
  at webpack:////home/circleci/project/node_modules/knex/node_modules/pg-connection-string/index.js?:4:141
  
  Error: Cannot find module 'fs'
      at webpackMissingModule (webpack:////home/circleci/project/node_modules/knex/node_modules/pg-connection-string/index.js?:4:74)
      at eval (webpack:////home/circleci/project/node_modules/knex/node_modules/pg-connection-string/index.js?:4:151)
      at Object.../../node_modules/knex/node_modules/pg-connection-string/index.js (test/mutations.test.js:8163:1)
      at __webpack_require__ (test/mutations.test.js:20:30)
      at eval (webpack:////home/circleci/project/node_modules/knex/lib/util/parse-connection.js?:2:19)
      at Object.../../node_modules/knex/lib/util/parse-connection.js (test/mutations.test.js:8140:1)
      at __webpack_require__ (test/mutations.test.js:20:30)
      at eval (webpack:////home/circleci/project/node_modules/knex/lib/knex.js?:7:25)
      at Object.../../node_modules/knex/lib/knex.js (test/mutations.test.js:7876:1)
      at __webpack_require__ (test/mutations.test.js:20:30)
      at eval (webpack:////home/circleci/project/node_modules/knex/lib/index.js?:1:14)
      at Object.../../node_modules/knex/lib/index.js (test/mutations.test.js:7854:1)
      at __webpack_require__ (test/mutations.test.js:20:30)
      at eval (webpack:////home/circleci/project/node_modules/knex/knex.js?:8:18)
      at Object.../../node_modules/knex/knex.js (test/mutations.test.js:7249:1)
      at __webpack_require__ (test/mutations.test.js:20:30)

Finished in 0.233 secs / 0 secs @ 12:00:47 GMT+0000 (Coordinated Universal Time)

SUMMARY:
✔ 0 tests completed
[12:00:47] 'test' errored after 6 s
[12:00:47] Error: karma tests failed with code: 1
    at /home/circleci/project/examples/karma/gulpfile.js:49:18
    at removeAllListeners (/home/circleci/project/examples/karma/node_modules/karma/lib/server.js:370:9)
    at /home/circleci/project/examples/karma/node_modules/karma/lib/server.js:381:13
    at Server.close (net.js:1592:9)
    at Object.onceWrapper (events.js:299:28)
    at Server.emit (events.js:215:7)
    at Server.EventEmitter.emit (domain.js:498:23)
    at emitCloseNT (net.js:1645:8)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1

```
https://app.circleci.com/jobs/github/aerogear/graphql-testx/418
https://github.com/aerogear/graphql-testx/pull/120

**Comment by wtrocki** [comment]
So it looks like we are trying to run node.js api in the context of the browser?
Would testx work always with node but then there is karma stuff. 
I guess that all of the tests should be running in Node.js where fs is satisfied?

**Comment by b1zzu** [comment]
> So it looks like we are trying to run node.js api in the context of the browser?

Exactly, because the `index.ts` is importing also the `TestxServer` and the `TestxController` and they require node.js, but the `TestxDirector` can work also without it

> Would testx work always with node but then there is karma stuff.
> I guess that all of the tests should be running in Node.js where fs is satisfied?

That's the reason why I've created the `TestxController` and the `TestxDirector`, the director will talk to the controller with a basic http API in order to controller the server wrapped inside the controller

To resume, we can use testx together with Karma thanks to the `TestxDirector` but to avoid importing also the other classes we have to import the director using the full path `graphql-testx/dist/src/TestxDirector`

**Comment by wtrocki** [comment]
Then spliting to packages can be good thing, but also building different targets and having mappers can be also good idea: 
https://www.npmjs.com/package/browserify-fs
